apiVersion: apps/v1
kind: Deployment
metadata:
  name: mefki-deployment
  labels:
    app: mefki
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mefki
  template:
    metadata:
      labels:
        app: mefki
    spec:
      containers:
        - name: mefki
          image: gcr.io/protean-cistern-237514/mefki:v4
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "mefki-1-hpa"
  namespace: "default"
  labels:
    app: "mefki"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "mefki-deployment"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        targetAverageUtilization: 80
