apiVersion: v1
kind: ReplicationController
metadata:
  name: mefki2
spec:
  replicas: 1
  selector:
    app: mefki2
  template:
    metadata:
      name: mefki2
      labels:
        app: mefki2
    spec:
      containers:
        - name: mefki2
          image: gcr.io/protean-cistern-237514/mefki2:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              hostPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mefki2service
  name: mefki2service
spec:
  ports:
    # The port that this service should serve on.
    - port: 80
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: mefki2
  type: LoadBalancer
