[package]
name = "rust-backend"
version = "0.1.0"
authors = ["bartek <bartosz.kakol@codilime.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
csv = "1"
reqwest = {version = "0.9.14", features = ["hyper-011"]}
